version: '2'
services:
  web:
    build: .
    volumes:
      - /app/log
    depends_on:
      - test-db

  test-db:
    image: mysql
    environment:
      MYSQL_DATABASE: docker_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
