version: '3'
services:
  app:
    build:
      context: .
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_password
      - MYSQL_USER=user_name
      - MYSQL_PASSWORD=user_password
      - RAILS_ENV=production
      - AWS_ACCESS_KEY_ID=AKIAXOA4RC3I7QE2KA4T
      - AWS_SECRET_ACCESS_KEY=BONFRiCHSB5MVmPLtm/ATcu+RYXMUI+Dih0N
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_password
      - MYSQL_USER=user_name
      - MYSQL_PASSWORD=user_password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
