version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose -f docker-compose.yml build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose -f docker-compose.yml up -d
      - run:
          name: db接続を待機
          command: sleep 10
      - run:
          name: データの権限のセットsアップ
          command: docker-compose exec db mysql -u root -pdb_root_password -e"$(cat db/grant_user.sql)"
      - run:
          name: データベースのセットアップ
          command: docker-compose -f docker-compose.yml run app rails db:create
      - run:
          name: データの実行環境の
          command: docker-compose -f docker-compose.yml run app rails db:environment:set
      - run:
          name: データベースのマイグレート
          command: docker-compose -f docker-compose.yml run app rails db:migrate
      - run:
          name: webpackerの実行
          command: docker-compose -f docker-compose.yml run app rails webpacker:install
      - run:
          name: Rubocopの実行
          command: docker-compose -f docker-compose.yml run app bundle exec rubocop
      - run:
          name: Rspecの実行
          command: docker-compose -f docker-compose.yml run app bundle exec rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose -f docker-compose.yml down
