version: 2.1
jobs:
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: bundle install
          command: docker-compose run app bundle install
      - run:
          name: setup db
          command: docker-compose run app rails db:create db:migrate
      - run:
          name: seed db
          command: docker-compose exec app rails db:seed
      - run:
          name: rspec
          command: docker-compose exec app rspec
      - run:
          name: docker-compose down
          command: docker-compose down


workflows:
  test_workflow:
    jobs:
      - test:
        filters:
          branches:
            only:
            - task-1
