version: 2.1
jobs:
  test:
    working_directory: ~/techbooks
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          command: |
            docker-compose up -d
      - run:
          command: |
            docker-compose exec techbooks_app_1 bash -c 'yes n | bundle exec rails g spree:install --migrate --seed --sample --auto_accept'
      - run:
          command: docker-compose exec techbooks_app_1 rspec


workflows:
  test_workflow:
    jobs:
      - test:
        filters:
          branches:
            only:
            - task-1
