default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webapp_development
  host: db
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>

test:
  <<: *default
  database: myapp_test
  host: db
  username: postgres
  password:

production:
  <<: *default
  database: webapp_production
  host: ENV['DATABASE_HOST']
  username: ENV['DATABASE_USER_NAME']
  password: ENV['DATABASE_PASSWORD']
